### ISSUE TITLE
Improved Shiki (Shikiji) for Markdown-It

### ISSUE THREAD

**Issue by secondmanveran** [Snapstromegon/hoeser.dev#349]
Hello Raphael,

I just came across your [article](https://www.hoeser.dev/blog/2023-02-01-syntax-highlight/) from last Feb on Improved Syntax Highlighting. 

I used your original post on Skiki to create some really nice CSS variables. 

But I use Markdown-It and the `shikiji-markdown-it` plugin and I'm wondering if there's a way to implement your "shikier" customizations for Markdown-It as opposed to Eleventy?

If you have any thoughts I'd love to hear them. I'm not a huge javascript person but even if you can tell me what I need to remove from your file that would be a huge help.

Thanks

**Comment by Snapstromegon** [comment]
Hey @secondmanveran,
thanks for commenting.
I was not aware of either the shikiji esm rewrite, nor the markdown plugin.
After taking a first look, it should definetly be possible, since my version from the blogpost also only amends the markdown-it plugin that is used within 11ty.

To make it a simple example at first, you could start with this:
```js
// some code where you configure markdown-it
import { getHighlighter } from 'shikiji';
const highlighter = await getHighlighter({/* your shikiji options */});
mdLib.set({
    highlight: (code, lang) => highlighter.codeToHtml(code, { lang }),
});
```

If this works correctly, you can go ahead and replace the line with `.codeToHtml` with the `highlight` function from my blogpost.
To get that function, you can copy my shikier js file into your project:
https://github.com/Snapstromegon/hoeser.dev/blob/main/lib/shikier/index.cjs

And change the `module.exports` to:
```js
module.exports = { highlight }
```

So your resulting code should look like this:
```js
// some code where you configure markdown-it
import { getHighlighter } from 'shikiji';
import { highlight } from './shikier.js';
const highlighter = await getHighlighter({/* your shikiji options */});
mdLib.set({
    highlight: (code, lang) => highlight(code, lang, highlighter),
});
```

> Disclaimer: I didn't test this, but I think this should work.

**Comment by Snapstromegon** [comment]
Since I haven't heard back from this and also shiki releasing a breaking change, I'm closing this issue.
